version: '3.9'
services:
    filebrowser:
        image: 'filebrowser/filebrowser'
        container_name: filebrowser
        restart: unless-stopped
        network_mode: bridge
        ports:
            - '4080:80'
        environment:
            - PGID=1000
            - PUID=1000
        volumes:
            - '/home/frosty/AppData/filebrowser/.filebrowser.json:/config/.filebrowser.json'
            - '/home/frosty/AppData/filebrowser/filebrowser.db:/database/filebrowser.db'
            - '/home/frosty/:/srv'