---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/AppData/homeassistant/config:/config
    ports:
      - 8123:8123
    restart: unless-stopped