version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8800:80/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: 'pi-hole@2023'
    volumes:
      - '/home/frosty/AppData/pihole/etc-pihole:/etc/pihole'
      - '/home/frosty/AppData/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped