version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
          dockervlan:
            ipv4_address: 192.168.10.10
          intranet:
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /home/frosty/AppData/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations

networks:
  dockervlan:
    external: true
  intranet:
    external: true