version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
          intranet:
          speedtest-tracker_network:
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /home/frosty/AppData/homepage/config:/app/config # Make sure your local config directory exists
      - /home/frosty/AppData/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations


networks:
  intranet:
    external: true
  speedtest-tracker_network:
    external: true
