version: '3'
services:
    adguardhome:
        container_name: adguardhome
        image: adguard/adguardhome:latest
        networks:
          dockervlan:
            ipv4_address: 192.168.101.53
        restart: unless-stopped
        volumes:
            - /home/frosty/AppData/adguardhome/workdir:/opt/adguardhome/work
            - /home/frosty/AppData/adguardhome/confdir:/opt/adguardhome/conf
            - /home/frosty/AppData/nginxproxymanager/letsencrypt/live/npm-3/fullchain.pem:/opt/adguardhome/certs/fullchain.pem
            - /home/frosty/AppData/nginxproxymanager/letsencrypt/live/npm-3/privkey.pem:/opt/adguardhome/certs/privkey.pem
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 67:67/udp
            - 68:68/udp
            - 80:80/tcp
            - 443:443/tcp
            - 443:443/udp
            - 3000:3000/tcp
            - 853:853/tcp
            - 784:784/udp
            - 853:853/udp
            - 8853:8853/udp
            - 5443:5443/tcp
            - 5443:5443/udp

networks:
  dockervlan:
    external: true