version: '3'
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actualbudget
    network_mode: intranet
    ports:
      - '5006:5006'
    environment:
       - ACTUAL_HTTPS_KEY=/data/certs/privkey.pem
       - ACTUAL_HTTPS_CERT=/data/certs/cert.pem
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
       - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      - /home/frosty/AppData/actualbudget/data:/data
      - /home/frosty/AppData/nginxproxymanager/letsencrypt/live/npm-3/privkey.pem:/data/certs/privkey.pem
      - /home/frosty/AppData/nginxproxymanager/letsencrypt/live/npm-3/cert.pem:/data/certs/cert.pem
    restart: unless-stopped