version: '3'
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actualbudget
    network_mode: caddy.net
    ports:
      - '5006:5006'
    environment:
      - ACTUAL_PORT=5006
      - ACTUAL_HTTPS_KEY=/data/certs/privkey.pem
      - ACTUAL_HTTPS_CERT=/data/certs/cert.pem
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    volumes:
      - /opt/AppData/actualbudget/data:/data
      - /home/apps/AppData/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/wildcard_.web.techlab.page/wildcard_.web.techlab.page.crt:/data/certs/cert.pem
      - /home/apps/AppData/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/wildcard_.web.techlab.page/wildcard_.web.techlab.page.key:/data/certs/privkey.pem
    restart: unless-stopped