version: '3'
services:
  esphome:
    container_name: esphome
    network_mode: host
    image: ghcr.io/esphome/esphome
    volumes:
      - /home/frosty/AppData/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always