version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    networks:
          intranet:
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/frosty/AppData/nginxproxymanager/data:/data
      - /home/frosty/AppData/nginxproxymanager/letsencrypt:/etc/letsencrypt
networks:
  intranet:
    external: true